inherit_gem:
  gitlab-styles:
    - rubocop-default.yml

AllCops:
  TargetRubyVersion: 2.5
  TargetRailsVersion: 5.0
  UseCache: true
  CacheRootDirectory: tmp
  Exclude:
    - 'config/**/*'
    - 'script/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'db/**/*'
    - 'scripts/**/*'
    - 'lib/**/*'
    - 'tmp/**/*'
    - 'log/**/*'
    - 'bin/**/*'
    - 'doc/**/*'
    - 'spec/**/*' # Remove when we write good tests!
    - 'Rakefile'
    - 'Gemfile'

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Metrics/AbcSize:
  Max: 20

Metrics/MethodLength:
  Max: 25
