AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.5
  UseCache: true
  CacheRootDirectory: tmp
  NewCops: disable
  Exclude:
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'scripts/**/*'
    - 'log/**/*'
    - 'doc/**/*'
    - 'db/**/*'
    - 'bin/*'
    - 'Rakefile'

# == Metrics == #
Metrics/MethodLength:
  Max: 10

Metrics/ClassLength:
  Max: 100

Metrics/ModuleLength:
  Max: 100

Metrics/ParameterLists:
  Max: 5

# == Layout == #
Layout/LineLength:
  Max: 150

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle:      table

Layout/EmptyLineAfterGuardClause:
  Enabled: true

Layout/ExtraSpacing:
  ForceEqualSignAlignment: true

Layout/IndentationStyle:
  IndentationWidth: 2

# == Style == #
Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

Style/CollectionMethods:
  Enabled: true

# == Disabled Cops == #
Style/Documentation:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
