language: ruby
cache: bundler
sudo: required
dist: trusty
addons:
    postgresql: "9.6"
    chrome: stable

services:
    - postgresql
    - redis-server
    - docker

rvm:
  - 2.5.1

env:
  global:
    - DB=postgres

before_script:
  - cp config/application.yml.example config/application.yml
  - psql -c 'create database crowdai_test;' -U postgres

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - docker pull localstack/localstack
  - docker run -d -p 4572:4572 localstack/localstack
  - mkdir ~/fog
  - sleep 10 # give xvfb and localstack some time to start

script:
  - bundle exec rake db:migrate
  - bundle exec rake spec

branches:
  only:
    - master
    - staging
