language: ruby
cache: bundler
sudo: required
dist: xenial
addons:
    postgresql: "9.6"
    chrome: stable

services:
    - postgresql
    - redis-server
    - docker
    - xvfb

rvm:
  - 2.5.5

env:
  global:
    - DB=postgres
    # Start only s3 on localstack
    - SERVICES=s3

before_script:
  - cp config/application.yml.example config/application.yml
  - psql -c 'create database crowdai_test;' -U postgres

before_install:
  - docker pull localstack/localstack
  - docker run -d -e SERVICES="s3" -e LOCALSTACK_HOSTNAME="localhost" -e LOCALSTACK_HOSTNAME="localhost" -p 8080:8080  -p 4572:4572 -v "/tmp/localstack:/tmp/localstack" -v "/var/run/docker.sock:/var/run/docker.sock" -e DOCKER_HOST="unix:///var/run/docker.sock" -e HOST_TMP_FOLDER="/tmp/localstack" "localstack/localstack" 
  - mkdir ~/fog
  - sleep 2 # give xvfb and localstack some time to start

script:
  - bundle exec rake db:migrate
  - bundle exec rake spec

branches:
  only:
    - master
    - staging
