default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: aicrowd_production
  name: postgres
  password: sadhguru

staging:
  <<: *default
  database: crowdai_development

test:
  <<: *default
  database: aicrowd_production
  name: postgres
  password: sadhguru

production:
  <<: *default
  database: crowdai_production
  name: crowdai
  password: <%= ENV['CROWDAI_DATABASE_PASSWORD'] %>
