badges_daily:
  cron: "30 2 * * *" # 2:30 AM every day
  class: "BadgesDailyJob"

discourse_badges_daily:
  cron: "30 2 * * *" # 2:30 AM every day
  class: "DiscourseBadgesDailyJob"

terminate_challenges:
  cron: "*/10 * * * *" # Every 10 minutes
  class: "TerminateChallengesJob"
